### ISSUE TITLE
Suggestion to use `fixest` instead of `lfe`

### ISSUE THREAD

**Issue by statzhero** [iangow/farr#12]
Is there a reason you prefer to use `lfe::felm()` instead of `fixest::feols()`? 

Apparently the former is just barely maintained, and someone even wrote a translation package: https://github.com/grantmcdermott/lfe2fixest

Book seems to come together very nicely!

**Comment by iangow** [comment]
No particular reason other than path-dependence (what I had used before). At some point I could look at replacing `life::felm()`, but probably after the whole book is somewhat complete. (I'd would need to do a global replacement.)

The same issue explains `%>%` in place of `>|` and use of `stargazer` (I'm told there are better alternatives now).

**Comment by iangow** [comment]
@statzhero Done. Also updated the book to use the native pipe (`|>`). See [here](https://iangow.github.io/far_book/#sec-recent)
