### ISSUE TITLE
Update `case_when` for readability

### ISSUE THREAD

**Issue by statzhero** [iangow/farr#15]
I saw you made some modernizing updates in July. Here is one I strongly recommend: `dplyr::case_when()` now allows you to specify a default value with the `.default` argument. It is much more readable than say `FALSE ~ TRUE`, in my view. I couldn't find the R / package version to build the book, so it'll only work with 1.1.0 or above.

For example, related to table 7.3 we would have 

```r
case_when(!is.na(che) ~ che,
          !is.na(ivst) ~ ivst,
          !is.na(ch) ~ ch,
          .default = NA)
```
instead of 

```r
funda_mod |>
  select(gvkey, datadate, che, ch, ivst) |>
  mutate(missing_che = is.na(che),
         missing_che_comps = is.na(ch) & is.na(ivst),
         che = case_when(!is.na(che) ~ che,
                         !is.na(ivst) ~ ivst,
                         !is.na(ch) ~ ch,
                         FALSE ~ NA),
         che_calc = coalesce(ch, 0) + coalesce(ivst, 0),
         che_diff = che_calc - che,
         che_balance = abs(che_diff) < tol) |>
  count(che_balance, missing_che, missing_che_comps) |>
  collect() |>
  arrange(desc(n))
```

**Comment by iangow** [comment]
Note that `FALSE ~ NA` does nothing. I changed everything to use `.default` (except where I had `TRUE ~ NA`, which I simply dropped).
