### ISSUE TITLE
no wrds access 

### ISSUE THREAD

**Issue by ssoro** [iangow/farr#16]
I recently had the opportunity to delve into the captivating chapters of your book, and I couldn't help but notice its strong reliance on WRDS access. While this enriches the experience for those who have WRDS access, it might limit the usefulness for individuals (like me) who lack such privilege.

With that in mind, I was wondering if it might be feasible to offer an alternative for these readers without WRDS access. Is there any possibility of providing easily accessible offline data or perhaps supplementing the book with online resources like Google Drive? This would undoubtedly enhance the book's appeal and make the valuable insights provided more widely accessible to all interested readers.

**Comment by iangow** [comment]
Unfortunately, that would not be possible.

First, there are licensing issues. I can't simply download proprietary data and put them in Google Drive.
Second, it would be a *lot* of work to rework the book to include the process of creating a database and importing data from Google Drive and to curate the required data. (A database would be the only way to handle tables as large as 20GB without further reworking the code to use `data.table` or similar.)

Note that you can get through the first five chapters (and chapter 9) without WRDS.
