### ISSUE TITLE
ccmxpf_linktable versus ccmxpf_lnkhist

### ISSUE THREAD

**Issue by waynelapierre** [iangow/farr#2]
Thank you so much for writing and sharing this great book about financial accounting research. I have a question about the use of ccmxpf_linktable versus ccmxpf_lnkhist in linking Compustat and CRSP. 

In an older post, you mentioned that ccmxpf_linktable has been deprecated by WRDS. 
https://gist.github.com/iangow/583557b7b91a87ee1e545aa839ccbb8d

In a more recent post, you find that ccmxpf_linktable and ccmxpf_lnkhist can generate the same merging result. 
https://gist.github.com/iangow/fca4cb10b048f5c798113da7039c2688

This makes me wonder if ccmxpf_linktable has been deprecated, why is it still working? 

This old WRDS tutorial uses ccmxpf_linktable and is followed by many. 
https://wrds-www.wharton.upenn.edu/pages/support/applications/linking-databases/linking-crsp-and-compustat/

So I am not sure if using ccmxpf_linktable would be a problem. Thanks.

**Comment by iangow** [comment]
It seems that you can use `ccmxpf_linktable` without problems (WRDS seems not to have followed through with its earlier "deprecation"), but it's constructed from `ccmxpf_linktable` and so there's no reason not to just use the latter table.
