### ISSUE TITLE
merge 4th quarter rdq with comp.funda 

### ISSUE THREAD

**Issue by waynelapierre** [iangow/farr#4]
I saw that you used gvkey and datadate to merge 4th quarter rdq with comp.funda. 
```
annc_dates <-
  firm_years %>%
  inner_join(rdqs, by = c("gvkey", "datadate")) %>%
  filter(datadate >= "2000-01-01") 
```
This makes sense but I feel more comfortable with using gvkey and fyear (fyearq in comp.fundq). I tried it and found that using gvkey and fyear generates more observations than using gvkey and datadate.

**Comment by iangow** [comment]
> I tried it and found that using gvkey and fyear generates more observations than using gvkey and datadate.

But there's no assurance that more matches means better matches. My guess is that you're picking up some bad matches (e.g., the "wrong" quarters or changes in fiscal year-ends). I think this is examined somewhere in the book too.
