### ISSUE TITLE
Matching by datadate versus rdq

### ISSUE THREAD

**Issue by waynelapierre** [iangow/farr#5]
Regarding section 9.2.1 Applying the CRSP-Compustat link,
http://iangow.me/far_2021/ident.html#applying-the-crsp-compustat-link.  

My personal understanding is that when testing how financial markets react to corporate financial disclosures, merging by rdq should be used to make sure that market participants have access to the disclosed information. When testing how corporate policy reacts to financial markets, merging by datadate should be used. What do you think? Thanks.

**Comment by waynelapierre** [comment]
do you mind answering my question? thanks.

**Comment by iangow** [comment]
> My personal understanding is that when testing how financial markets react to corporate financial disclosures, merging by rdq should be used to make sure that market participants have access to the disclosed information. When testing how corporate policy reacts to financial markets, merging by datadate should be used. 

I would expect the market to react to earnings announcements on `rdq` (or the day after if after trading hours). I don't know what is being "merged" here. I don't understand the second sentence.

**Comment by waynelapierre** [comment]
For example, if I need to test whether stock repurchases affect stock volatility, I would merge Compustat and CRSP with gvkey and rdq so investors have access to the repurchase information on announcement dates. If I need to test whether stock volatility affects stock repurchases, I would merge Compustat and CRSP with gvkey and datadate to match the calendar year (quarter). Is my understanding of your book correct? Thanks.

**Comment by iangow** [comment]
I don't think it's that simple (and I don't think the book addresses these cases explicitly). I think we say in the book that a lot depends on your research question and measures. If investors are getting information about stock repurchases from 10-Qs, then you should use `rdq` dates to determine their information set. But I'm not sure that `datadate` in any way proxies for when firms learn about stock volatility (this would be more a function of the *period* over which such volatility is measured).

**Comment by waynelapierre** [comment]
Thank you so much for the clarification!
