### ISSUE TITLE
A mislabeling in Chapter 5 Statistical inference of Accounting Research: An Introductory Course”.

### ISSUE THREAD

**Issue by wyih** [iangow/farr#6]
First of all, thank you for sharing your course material. Even though I am only half way through the Chapter 5, I've already learned a lot from it.

Just one minor suggestion and I might be wrong. In the last table of [5.1.2](http://iangow.me/far_2021/stat-inf.html#fama-macbeth), I think the `FM-i` should be `FM-t`.

**Comment by iangow** [comment]
@wyih Thanks. Fixed now, I believe.

**Comment by wyih** [comment]
I've found other typos and I don't want to open a new issue, so I guess I will just leave the comment here.

`get_data`function in [20.4](http://iangow.me/far_2021/misc-methods.html#appendix-simulation-study-from-leone2019uc) 
```
contaminated = case_when(!clean & !random ~ id < prop_cont * n & x1 < -1.5,
                                                !clean & !random ~ id < prop_cont * n,
                                                TRUE ~ FALSE),
```
I think `!clean & !random ~ id < prop_cont * n,` should be `!clean & random ~ id < prop_cont * n,`

And in [23.2](http://iangow.me/far_2021/panel-data.html#voluntary-disclosure)
```
pg <- dbConnect(RPostgres::Postgres(), bigint = "integer")
seg_customer <- tbl(pg, sql("SELECT * FROM compsegd.seg_customer"))
names_seg <- tbl(pg, sql("SELECT * FROM compsegd.names_seg"))
funda <- tbl(pg, sql("SELECT * FROM comp.funda"))
```
will throw error `ERROR:  relation "compsegd.seg_customer" does not exist`.

I change `compsegd` to `comp_segments_hist_daily` and get the codes running
